require 'date'
require File.dirname(__FILE__) + '/../../lib/serial_number.rb'

describe SerialNumber do
  before do
    @time_piece = DateTime.now.strftime('%Y%m%d%H%M')
  end
  it "has a number (autogenerated!)" do
    SerialNumber.number.should_not be_nil
  end
  specify "the autogenerated serial number should be date-time based" do
    SerialNumber.number.should match(@time_piece)
  end
  it "accepts a serial number" do
    lambda { SerialNumber.number = 123456 }.should_not raise_error
  end
  specify "the newly set number should be the serial number" do
    SerialNumber.number = 987654
    SerialNumber.number.should == "987654"
  end
  it "has a to_s method" do
    SerialNumber.number = 112233445566
    SerialNumber.to_s.should == '112233445566'
  end
  specify "this is cool: evaluate in string context, and class name returns the serial number!" do
    SerialNumber.number = 333444555
    "(#{SerialNumber})".should == '(333444555)'
  end
  it "accepts a prefix" do
    lambda { SerialNumber.prefix = 'bar' }.should_not raise_error
  end
  specify "the number should begin with the prefix" do
    SerialNumber.prefix = 'baz'
    SerialNumber.number.should match(/^baz/)
  end
end
